---
- name: Assert new password is different from default
  ansible.builtin.assert:
    msg: "Sonarqube password must different than default one"
    that:
      - sonarqube_configuration_sonarqube_password != sonarqube_configuration_sonarqube_default_password

- name: Change default password if needed
  ansible.builtin.uri:
    method: POST
    url: "{{ sonarqube_configuration_sonarqube_url }}/api/users/change_password?login={{ sonarqube_configuration_sonarqube_username }}&previousPassword={{ sonarqube_configuration_sonarqube_default_password }}&password={{ sonarqube_configuration_sonarqube_password }}"
    status_code: [204, 401]
    url_username: "{{ sonarqube_configuration_sonarqube_username }}"
    url_password: "{{ sonarqube_configuration_sonarqube_default_password }}"
    validate_certs: "{{ sonarqube_configuration_validate_certs }}"
    force_basic_auth: true
  register: change_default_password_result
  changed_when: change_default_password_result.status == 204
