---
- name: Backup database block
  block:

  - name: Ensure backup location exists
    ansible.builtin.file:
      path: "{{ sonarqube_backup_location }}"
      state: directory
      mode: '0755'

  - name: Backup database
    community.postgresql.postgresql_db:
      login_host: "{{ sonarqube_configuration_external_db_host }}"
      port: "{{ sonarqube_configuration_external_db_port }}"
      db: "{{ sonarqube_configuration_db_name }}"
      login_user: "{{ sonarqube_configuration_db_login }}"
      login_password: "{{ sonarqube_configuration_db_password }}"
      state: dump
      target: "{{ sonarqube_configuration_sonarqube_backup_location }}/sonarqube_backup_{{ ansible_date_time.epoch }}.tar"
      target_opts: "-F tar"
  when:
    - sonarqube_configuration_external_db_host is defined
    - sonarqube_configuration_external_db_port is defined
    - sonarqube_configuration_db_login is defined
    - sonarqube_configuration_db_password is defined
