---
- name: Create group
  ansible.builtin.uri:
    method: POST
    url: "{{ sonarqube_configuration_sonarqube_url }}/api/user_groups/create?name={{ group.name | urlencode() }}&description={{ group.description | urlencode() }}"
    status_code: [200, 400]
    url_username: "{{ sonarqube_configuration_sonarqube_username }}"
    url_password: "{{ sonarqube_configuration_sonarqube_password }}"
    validate_certs: "{{ sonarqube_configuration_validate_certs }}"
    force_basic_auth: yes
  changed_when: create_user_output.status == 200
  when: not group.deleted
  register: create_user_output

- name: Delete group
  ansible.builtin.uri:
    method: POST
    url: "{{ sonarqube_configuration_sonarqube_url }}/api/user_groups/delete?name={{ group.name }}"
    status_code: [204, 404]
    url_username: "{{ sonarqube_configuration_sonarqube_username }}"
    url_password: "{{ sonarqube_configuration_sonarqube_password }}"
    validate_certs: "{{ sonarqube_configuration_validate_certs }}"
    force_basic_auth: yes
  changed_when: create_user_output.status == 200
  when: group.deleted
  register: create_user_output
