namespace: jonesbusy
name: devops_collection
version: 0.0.1
readme: README.md
authors:
- Valentin Delaye <jonesbusy@gmail.com>
description: A collection of ansible roles and plugin to manage a devops toolchain
license:
- Unlicense
tags: []
dependencies:
  ansible.posix: 1.3.0
  community.general: 4.0.2
  community.postgresql: 1.5.0
  community.docker: 2.0.1
  community.crypto: 2.0.1
repository: https://github.com/jonesbusy/ansible-devops-collection
documentation: https://github.com/jonesbusy/ansible-devops-collection
homepage: https://github.com/jonesbusy/ansible-devops-collection
issues: https://github.com/jonesbusy/ansible-devops-collection
build_ignore: []

