---
- name: Delete blobstore {{ blobstore.name }}
  ansible.builtin.uri:
    method: DELETE
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/blobstores/{{ blobstore.name }}"
    status_code: [204, 404]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  register: nexus_result
  when: blobstore.deleted
  changed_when: nexus_result.status == 204

- name: Retrieve blobstore {{ blobstore.name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/blobstores/file/{{ blobstore.name }}"
    status_code: [200, 404]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  register: nexus_result
  when: not blobstore.deleted
  changed_when: nexus_result.status == 201

- name: Create blobstore {{ blobstore.name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/blobstores/file"
    status_code: [204]
    body_format: json
    body: "{{ lookup('template', 'blobstore.json.j2') }}"
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  when: not ansible_check_mode and not blobstore.deleted and nexus_result.status == 404
  changed_when: true

- name: Update blobstore {{ blobstore.name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/blobstores/file/{{ blobstore.name }}"
    status_code: [204]
    body_format: json
    body: "{{ lookup('template', 'blobstore.json.j2') }}"
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  when: not ansible_check_mode and not blobstore.deleted and nexus_result.status == 200
  changed_when: false
