---
- name: Ensure to change default password
  ansible.builtin.uri:
    method: PUT
    body_format: raw
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/security/users/{{ nexus_configuration_username }}/change-password"
    body: "{{ nexus_configuration_password }}"
    status_code: [204, 401]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_default_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
    headers:
      Content-Type: text/plain
  register: nexus_result
  changed_when: nexus_result.status == 204