---
- name: Delete repository privilege selectors
  ansible.builtin.uri:
    method: DELETE
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/security/privileges/{{ repository_content_selector.name }}"
    status_code: [204, 404]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  loop: "{{ nexus_repository_privileges_selectors }}"
  loop_control:
    loop_var: repository_content_selector
  register: nexus_result
  when: not ansible_check_mode and repository_content_selector.deleted
  changed_when: nexus_result.status == 204

- name: Delete content selectors
  ansible.builtin.uri:
    method: DELETE
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/security/content-selectors/{{ selector.name }}"
    status_code: [204, 404]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  loop: "{{ nexus_content_selectors }}"
  loop_control:
    loop_var: selector
  register: nexus_result
  when: not ansible_check_mode and selector.deleted
  changed_when: nexus_result.status == 204

# Content selectors
- name: Configure content selectors
  include_tasks: tasks/content_selector.yml
  loop: "{{ nexus_content_selectors }}"
  loop_control:
    loop_var: selector
  when: not ansible_check_mode and not selector.deleted

# Repository privileges selectors
- name: Configure content selectors
  include_tasks: tasks/repository_content_selector.yml
  loop: "{{ nexus_repository_privileges_selectors }}"
  loop_control:
    loop_var: repository_content_selector
  when: not ansible_check_mode and not repository_content_selector.deleted
