---
- name: Delete routing rules
  ansible.builtin.uri:
    method: DELETE
    url: "{{ nexus_configuration_nexus_url }}/service/rest/v1/routing_rules/{{ rule.name }}"
    status_code: [204, 404]
    url_username: "{{ nexus_configuration_username }}"
    url_password: "{{ nexus_configuration_password }}"
    validate_certs: "{{ nexus_configuration_validate_certs }}"
    force_basic_auth: yes
  loop: "{{ nexus_routing_rules }}"
  loop_control:
    loop_var: rule
  register: nexus_result
  when: not ansible_check_mode and rule.deleted
  changed_when: nexus_result.status == 204

- name: Configure routing_rules
  include_tasks: tasks/routing_rule.yml
  loop: "{{ nexus_routing_rules }}"
  loop_control:
    loop_var: rule
  when: not ansible_check_mode and not rule.deleted